### ISSUE TITLE
QA: interesting repo, have you come across the perl MOP?

### ISSUE THREAD

**Issue by konobi** [dritchie/terra-utils#1]
I've been looking into using terra for a few projects lately and came across your repo. I was just wondering if you've come across the Perl Meta Object Protocol that was brought into perl5 based on perl6 RFCs and whose use in production has heavily influenced the design and implementation that are in Perl6 now.

There's a lua implementation of the MOP available that you might want to check out:
https://fperrad.github.io/lua-Coat/

I'd be interested to hear if you have any insight into how useful this might be in terra?

**Comment by dritchie** [comment]
Provided it works with LuaJIT, you should be able to use this library with Terra (which is built atop LuaJIT). However, this would only provide an OO library for Lua objects. Terra objects (i.e. structs) require memory layout to specified, manual memory management, etc., so you need a separate OO library for Terra if you want to do OOP with your Terra code. That's what some of the code in this repo was intended to do (and has served that purpose for a couple of my own projects). I don't propose that the code in this repo should be "the standard" OO library for Terra code; I'm not the author of Terra, and that would be counter to the spirit of Terra, anyway. Rather, this is just one way to do it that I have found useful at some point. Your mileage may vary.

**Comment by konobi** [comment]
Yeah, I mention because it's a self hosting OO implementation which means you can change it's behaviour in <language> at compile-time or run-time. That seems to be in the spirit of terra =0)
